### ISSUE TITLE
Omxplayer can't play files located on external media

### ISSUE THREAD

**Issue by deyanyosifov** [ogra1/omxplayer-snap#5]
I think the problem is due to the strict confinement of snaps. After some reading, I think the problem can be overcome easily if the snap is allowed access to the removable-media interface by adding "removable-media" to the list of plugs in the snapcraft.yaml file and then building the snap. Would you do this?
https://snapcraft.io/docs/removable-media-interface

**Comment by ogra1** [comment]
added it to the snapcraft.yaml, the next build in the edge channel should have it
